# Numpy as np

In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
y=[1,2,3]
print(y)
print(type(y))


[1, 2, 3]
<class 'list'>


In [4]:
g=[7,8,6]
h=np.array(g)
print(h)
print(type(h))

[7 8 6]
<class 'numpy.ndarray'>


In [5]:
l=[]
for i in range(1,5):
    a=int(input("enter:"))
    l.append(a)
print(np.array(l))

enter:4
enter:4
enter:5
enter:4
[4 4 5 4]


In [6]:
ar2=np.array([[1,2,3],[5,5,6,]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [5 5 6]]
2


In [7]:
ar3=np.array([[[4,5,7],[5,2,8],[9,8,5]]])
print(ar3)
print(ar3.ndim)

[[[4 5 7]
  [5 2 8]
  [9 8 5]]]
3


In [8]:
arn= np.array([4,2,5],ndmin=8)
print(arn)
print(arn.ndim)

[[[[[[[[4 2 5]]]]]]]]
8


# zeros()

In [9]:
zeros=np.zeros(5)
print(zeros)
type(zeros)
print(zeros.ndim)

[0. 0. 0. 0. 0.]
1


In [10]:
zeros1=np.zeros((5,5)) 
print(zeros1)
type(zeros1)
print(zeros1.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


# ones()

In [11]:
ones=np.ones((5,4))
print(ones)
print(type(ones))
print(ones.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2


# empty()

In [12]:
em=np.empty((5,4))
print(em)
print(em.ndim)
print(type(em))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
<class 'numpy.ndarray'>


# arange() / Same as range function in python

In [5]:
rn=np.arange(5)
print(rn)
print(rn.ndim)
print(type(rn))

[0 1 2 3 4]
1
<class 'numpy.ndarray'>


# Diagonal / eye()

In [14]:
dia=np.eye(5)
print(dia)
print(dia.ndim)
print(type(dia))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
<class 'numpy.ndarray'>


In [2]:
dia=np.eye(5,5)
print(dia)
print(dia.ndim) 
print(type(dia))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
<class 'numpy.ndarray'>


# linspace() 

In [16]:
lp=np.linspace(0,10,num=5) #(Start value, stop value, incremented value)
print(lp)
print(lp.ndim)
print(type(lp))

[ 0.   2.5  5.   7.5 10. ]
1
<class 'numpy.ndarray'>


# Functions for Create Array of Random Values

# random.rand()

In [17]:
#create array of 1 dimension
var=np.random.rand(5)
print(var)
print(var.ndim)
print(type(var))


[0.9722058  0.46680038 0.75847717 0.58684911 0.47636002]
1
<class 'numpy.ndarray'>


In [18]:
#create array of mutliple dimension
var1=np.random.rand(2,2,5)
print(var1)
print(var1.ndim)
print(type(var1))

[[[0.47876317 0.02209734 0.89609708 0.19893965 0.49462264]
  [0.13868236 0.08000058 0.59651541 0.96265625 0.13358653]]

 [[0.01250787 0.78516544 0.77138806 0.32617385 0.58279327]
  [0.2223472  0.47334555 0.51208344 0.6419063  0.43533394]]]
3
<class 'numpy.ndarray'>


# random.randn()

In [19]:
var2=np.random.randn(5)
print(var2)
print(var2.ndim)
print(type(var2))

[ 0.79868959 -1.75139834  0.42955242 -0.26860688 -0.27966379]
1
<class 'numpy.ndarray'>


In [20]:
var2=np.random.randn(3,1,2)
print(var2)
print(var2.ndim)
print(type(var2))

[[[-2.302237    0.7057923 ]]

 [[ 0.20731096  0.36101034]]

 [[ 0.51011628 -0.55188118]]]
3
<class 'numpy.ndarray'>


# random.ranf()

In [21]:
var3=np.random.ranf(5)
print(var3)
print(var3.ndim)
print(type(var3))

[0.74977855 0.67830534 0.29411939 0.9448182  0.03789982]
1
<class 'numpy.ndarray'>


In [22]:
var3=np.random.ranf((2,3,1))
print(var3)
print(var3.ndim)
print(type(var3))

[[[0.48550366]
  [0.70427491]
  [0.34026587]]

 [[0.53966913]
  [0.07076683]
  [0.05183946]]]
3
<class 'numpy.ndarray'>


# random.randint()

In [23]:
var4=np.random.randint(2,20,5) #(min_value, max_value, total numbers in output)
print(var4)
print(var4.ndim)
print(type(var4))

[ 7  4 14  7 17]
1
<class 'numpy.ndarray'>


# Data Types in Numpy


# .dtype

In [24]:
va=np.array([1,2,3,5,8])
print(va)
print(va.dtype)

[1 2 3 5 8]
int32


In [25]:
x=np.array([1.2,2.6,5.3])
print(x)
print(x.dtype)

[1.2 2.6 5.3]
float64


In [26]:
x=np.array(["sameer","ansari"])
print(x)
print(x.dtype)

['sameer' 'ansari']
<U6


In [27]:
x=np.array(["sameer","ansari",7,8,6])
print(x)
print(x.dtype)

['sameer' 'ansari' '7' '8' '6']
<U11


In [28]:
#Change array data type to another data type
x=np.array([1,2,3],dtype=np.int64)
print(x)
print(x.dtype)

[1 2 3]
int64


In [29]:
x=np.array([1,2,3])
y=np.float32(x)
z=np.int_(y)

print(x)
print(y)
print(z)

print(x.dtype)
print(y.dtype)
print(z.dtype)


[1 2 3]
[1. 2. 3.]
[1 2 3]
int32
float32
int32


# .astype()

In [30]:
#change the data type of a array
x=np.array([1,2,3,5])
y=x.astype(float)
print(x)
print(y)
print(x.dtype)
print(y.dtype)

[1 2 3 5]
[1. 2. 3. 5.]
int32
float64


# Arithmetic Operation in Numpy

# # All the arithmetic operations are same like (+,-,*,/,**,%)

# #arithmetic operations in 1D Array

# Addition(+)

In [31]:
x=np.array([1,5,2,8]) 
add=x+3 
print(add) 
print(type(x)) 
print(x.ndim) 
print(x.dtype)

[ 4  8  5 11]
<class 'numpy.ndarray'>
1
int32


In [32]:
x=np.array([1,2,5,8])
y=np.array([2,5,3,9])
add=x+y
print(add)

[ 3  7  8 17]


# arithmetic operations in 2D array

# code for all the arithmetic operations are same as below. (+,-,/,*,%,**)

In [33]:
x1=np.array([[1,2,5],[2,5,8]])
x2=np.array([[5,8,3],[5,7,1]])

print(x1)
print(x2)
print()
print(x1.dtype)
print(x2.dtype)
print()
print(x1.ndim)
print(x2.ndim)

x3=x1+x2
print(x3)
print()
print(x3.dtype)
print(x3.ndim)


[[1 2 5]
 [2 5 8]]
[[5 8 3]
 [5 7 1]]

int32
int32

2
2
[[ 6 10  8]
 [ 7 12  9]]

int32
2


# Arithmetic Functions in Numpy


In [34]:
# np.min() - find the minimum value in array
# np.max() - find the maximum value in array
# np.argmin() - find the index of minimum value
# np.argmax() - find the index of maximum value
# np.sqrt() - find the square root of a array
# np.sin() - find the sin value of array
# np.cos() - find the cos value of array
# np.cumsum() - add the values of a array by it's previous value. eg- input = [1,2,3], output = [1,3,6]. Useful in Statistics

In [35]:
#SAMPLE OF 1D ARRAY 

x=np.array([1,5,3,9,2,5,4])

print("min value is:", np.min(x))

print("max value is:", np.max(x))

print("index of min value:", np.argmin(x))

print("index of max value:", np.argmax(x))

min value is: 1
max value is: 9
index of min value: 0
index of max value: 3


In [36]:
#SAMPLE OF 2D ARRAY

x1=np.array([[1,5,3],[9,8,7]])

print(np.min(x1)) #Simple command

print(np.min(x1,axis=0)) # axis 0 = Column

print(np.min(x1,axis=1)) # axis 1 = Row

1
[1 5 3]
[1 7]


In [37]:
x=np.array([1,5,3,9,2,5,4])

print(np.sqrt(x))

[1.         2.23606798 1.73205081 3.         1.41421356 2.23606798
 2.        ]


In [38]:
x1=np.array([[1,5,3],[9,8,7]])

print(np.sqrt(x1))

[[1.         2.23606798 1.73205081]
 [3.         2.82842712 2.64575131]]


In [39]:
x2=np.array([1,5,9])

print("the sin value is:", np.sin(x2))

the sin value is: [ 0.84147098 -0.95892427  0.41211849]


In [40]:
x3=np.array([2,8,1])

print("the cos value is:", np.cos(x3))

the cos value is: [-0.41614684 -0.14550003  0.54030231]


In [41]:
x4=np.array([1,8,6,4,2,57,63])

print("the cumsum of array is:", np.cumsum(x4))

the cumsum of array is: [  1   9  15  19  21  78 141]


# .shape


# # It is use to find the shape of an array

In [42]:
x = np.array([[1,5,8],[5,8,3]])

print(x)
print()
print(x.dtype)
print()
print(type(x))
print()
print(x.ndim)
print()
print(x.shape)

[[1 5 8]
 [5 8 3]]

int32

<class 'numpy.ndarray'>

2

(2, 3)


In [43]:
x1 = np.array([4,2,8,7,3], ndmin=5)

print(x1)
print(x1.ndim)
print()
print(x1.shape)

[[[[[4 2 8 7 3]]]]]
5

(1, 1, 1, 1, 5)


# .reshape()

# It is use to change the shape of an array. Eg:- it changes a 1D array into 2D or multiple dimension array and vise versa.

In [44]:
x = np.array([1,2,3,4,5,6])
print(x)
print("the dimension of array is:",x.ndim)
y = x.reshape(3,2)
print(y)
print("the dimension of array is:",y.ndim)

[1 2 3 4 5 6]
the dimension of array is: 1
[[1 2]
 [3 4]
 [5 6]]
the dimension of array is: 2


In [45]:
x = np.array([1,2,3,4,5,6])
print(x)
print("the dimension of array is:",x.ndim)
y = x.reshape(3,3)
print(y)
print("the dimension of array is:",y.ndim)

[1 2 3 4 5 6]
the dimension of array is: 1


ValueError: cannot reshape array of size 6 into shape (3,3)

In [47]:
x2 = np.array([1,5,65,32,20,1,5,8,0,5,7,2]) #It is 1D array 

print(x2)
print("the dimension of array is:", x2.ndim)
print()
x3 = x2.reshape(2,3,2) #With the use reshape we change it into 3D array

print(x3)
print("the dimension of array is:", x3.ndim)
print()

x4 = x3.reshape(-1) # Change a 3D array into 1D array

print(x4)
print("the dimension of array is:", x4.ndim)

[ 1  5 65 32 20  1  5  8  0  5  7  2]
the dimension of array is: 1

[[[ 1  5]
  [65 32]
  [20  1]]

 [[ 5  8]
  [ 0  5]
  [ 7  2]]]
the dimension of array is: 3

[ 1  5 65 32 20  1  5  8  0  5  7  2]
the dimension of array is: 1


# Broadcasting in Numpy

In [3]:
#Addition of same or different Dimension array

x = np.array([1,2,3])

print(x)
print()
print(x.shape)
print()

x1 = np.array([[2],[7],[5]])

print(x)
print()
print(x1.shape)
print()
print(x+x1)

[1 2 3]

(3,)

[1 2 3]

(3, 1)

[[ 3  4  5]
 [ 8  9 10]
 [ 6  7  8]]


In [11]:
x = np.array([[1],[2]])
print(x.shape)
x1 = np.array([[1,2,3],[2,8,9]])
print(x1.shape)
print()
y = x+x1
print(y)
print(y.shape)

(2, 1)
(2, 3)

[[ 2  3  4]
 [ 4 10 11]]
(2, 3)


# Indexing 

In [13]:
#find index in 1D array
x = np.array([1,8,3,5])
             #0,1,2,3
            #-4,-3,-2,-1
print(x[0])
print(x[-4])

1
1


In [16]:
#find index in 2D array
x = np.array([[1,2,2],[2,8,9]])
print(x)
print(x.ndim)
print()
print(x[1,1])

[[1 2 2]
 [2 8 9]]
2

8


In [22]:
#find index in 3D array
x = np.array([[[1,5,6],[5,2,7],[2,9,1]]])
print(x)
print("the dimension of array is:",x.ndim)
print()
print(x[0,2,1])

[[[1 5 6]
  [5 2 7]
  [2 9 1]]]
the dimension of array is: 3

9


# Slicing

In [24]:
#Slicing in 1D array
x = np.array([1,5,3,8,5,2,7,8,8])
             #0,1,2,3,4,5,6,7,8
print(x[0:8:1])#start:stop:step
print(x[0::2])

[1 5 3 8 5 2 7 8]
[1 3 5 7 8]


In [28]:
#Slicing in 2D array
x = np.array([[1,5,3,8,5],[5,5,2,9,2]])
print(x)
print()
print(x.ndim)
print()
print(x[1,0:5:2])
print(x[0,1::1])

[[1 5 3 8 5]
 [5 5 2 9 2]]

2

[5 2 2]
[5 3 8 5]


# Iteration :- With the help of FOR Loop

In [30]:
#Iteration in 1D array
x = np.array([1,8,3,8,24,54])
print(x)
print()
for i in x:
    print(i)

[ 1  8  3  8 24 54]

1
8
3
8
24
54


In [43]:
#Iteration in 2D array
x = np.array([[1,2,3,4],[1,5,9,8]])
print(x)
print()
for i in x:
    for g in i:
        print(g)

[[1 2 3 4]
 [1 5 9 8]]

1
2
3
4
1
5
9
8


In [45]:
#Iteration in 3D array
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)
print(x.ndim)
print()

for i in x:
    for j in i:
        for h in j:
            print(h)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


# Iteration :- With the help of np.nditer()

In [ ]:
#This function work with FOR Loop.
#np.nditer() helpful in iteration of 2D or multiple dimension array. 

In [53]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) 
print(x) 
print(x.ndim) 
print()

for y in np.nditer(x): 
    print(y)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


# np.ndenumerate()

In [52]:
# This function helps to find the index values in a array. 
#Work with FOR Loop. 
#With the help of this function we perform iteration with index value at same time.


In [60]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) 
print(x) 
print(x.ndim) 
print()

for y,d in np.ndenumerate(x): 
    print(y,d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


# .copy() VS .view()

In [7]:
x = np.array([1,8,5])
y= x.copy()
y[2]=40
print("x = ",x)
print("y = ",y)

x =  [1 8 5]
y =  [ 1  8 40]


In [6]:
x = np.array([1,8,5])
y= x.view()
x[1]=20
print("x = ",x)
print("y = ",y)

x =  [ 1 20  5]
y =  [ 1 20  5]


# Join Array

# Join Array:- Joining means putting contents of two or more arrays in a single array.

# np.concatenate(()) :- this command combine two arrays and made a new array. 

In [10]:
#Joining of 1D arrays.
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


In [16]:
#joining of 2D or multi dimension arrays.
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
z = np.concatenate((x,y),axis=0)
print(z)

[[1 2 3]
 [4 5 6]]


# np.stack() :- it merge two array and make a new array.
# np.hstack() :- it merges arrays horizontally / rows.
# np.vstack :- it merges arrays vertically / columns.
# np.dstack :- it merges arrays height wise.

In [24]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.stack((x,y),axis=0)
print(z)
print()

a = np.hstack((x,y)) #row
print(a)
print()

b = np.vstack((x,y)) #column
print(b)
print()

c = np.dstack((x,y)) #height
print(c)


[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


# Split Array :- splitting breaks one array into multiple.

# np.split()

In [28]:
#splitting of 1D array
x = np.array([1,5,2,8,7,3])
y = np.split(x,2)
print(y)
print()
print(type(y))
print()
print(y[0])

[array([1, 5, 2]), array([8, 7, 3])]

<class 'list'>

[1 5 2]


In [46]:
#splitting of 2D or multi dimension arrays.
x = np.array([[1,5,2],[1,8,6],[4,4,2]])
y = np.split(x,3)
z = np.split(x,3,axis=1)
print(y)
print()
print(z)

[array([[1, 5, 2]]), array([[1, 8, 6]]), array([[4, 4, 2]])]

[array([[1],
       [1],
       [4]]), array([[5],
       [8],
       [4]]), array([[2],
       [6],
       [2]])]


# Search Array :- Search an array for a certain value, and return the indexes that get a match.


# np.where() :- in where function we write array variable and add , then we write the value and in output it gives the index number of that value in the array.
# We can perform any arithmetic functions and use operaters in np.where()

In [54]:
x = np.array([1,2,3,1,2,5,7,5,3,4,7])
y = np.where(x==2)
print(y)

(array([1, 4], dtype=int64),)


In [64]:
x = np.array([1,2,3,1,2,5,7,5,3,4,7])
y = np.where((x-2)==1)
z = np.where((x%3)==1)
print(y)
print()
print(z)

(array([2, 8], dtype=int64),)

(array([ 0,  3,  6,  9, 10], dtype=int64),)


# Search Sorted Array :- which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

# np.searchsorted()

In [84]:
x = np.array([1,2,3,6,7,8,9,10])
y = np.searchsorted(x,4)
z = np.searchsorted(x,[4,5])

print(y)
print(z)

3
[3 3]


# Sort Array :- Ordered sequence in any sequence that has an order corresponding to elements, like numeric, alphabetical, ascending or descending.

# np.sort() 

In [86]:
#example of 1D Array
x = np.array([1,8,7,3,2,4,9,10,15,12,10])
print(np.sort(x))

[ 1  2  3  4  7  8  9 10 10 12 15]


In [87]:
x = np.array(["a","g","c","z","b"])
print(np.sort(x))

['a' 'b' 'c' 'g' 'z']


In [89]:
#example of 2D or Multi dimension array
x = np.array([[1,8,7],[3,4,9],[10,15,10]])
print(np.sort(x))

[[ 1  7  8]
 [ 3  4  9]
 [10 10 15]]


# Filter Array :- Getting some elements out of an existing array and creating a new array out of them.

In [92]:
# We use this function to filter any datatype in array and it will create a new filtered array
x = np.array([1,5,8,9])
y = [True,False,False,True]
z = x[y]
print(z)

[1 9]


# Functions in Numpy
# 1. (Arithmetic Functions) :- Shuffle, Unique, Resize, Flatten, Ravel 

# np.random.shuffle()

In [102]:
x = np.array([1,5,78,52,21,2])
np.random.shuffle(x)
print(x)

[ 1  5 52  2 21 78]


In [103]:
# Note:- We cannot put np.random.shuffle() in a variable because it doesn't work.
x = np.array([1,5,78,52,21,2])
y = np.random.shuffle(x)
print(y)

None


# np.unique()

In [104]:
x = np.array([1,5,2,7,4,3,5,2,9,8])
y = np.unique(x)
print(y)

[1 2 3 4 5 7 8 9]


In [107]:
x = np.array([1,5,2,7,4,3,5,2,9,8])
y = np.unique(x,return_counts=True,return_index=True) # Parameters to find the index values and total counts of a array.
print(y)

(array([1, 2, 3, 4, 5, 7, 8, 9]), array([0, 2, 5, 4, 1, 3, 9, 8], dtype=int64), array([1, 2, 1, 1, 2, 1, 1, 1], dtype=int64))


# np.resize()

In [109]:
# Its helps in change a 1D array to 2D or Multi dimension array.
x = np.array([1,5,7,3,5,4,3,2])
y = np.resize(x,(4,2))
print(y)

[[1 5]
 [7 3]
 [5 4]
 [3 2]]


# .flatten()

In [110]:
# It converts a 2D array into 1D array.
x = np.array([[1,2],[2,5],[4,5],[9,8]])
print(x)
print()
print(x.flatten())

[[1 2]
 [2 5]
 [4 5]
 [9 8]]

[1 2 2 5 4 5 9 8]


# .ravel()

In [111]:
# Same as flatten()
# It converts a 2D array into 1D array.
x = np.array([[1,2],[2,5],[4,5],[9,8]])
print(x)
print()
print(x.ravel())

[[1 2]
 [2 5]
 [4 5]
 [9 8]]

[1 2 2 5 4 5 9 8]


# np.insert()


In [112]:
# It is use to insert a data into existing array.
# Note:- always insert a same data type as array because it doesn't accept changed data type.
# We can insert multiple data at multiple indexes.
x = np.array([1,2,5,7])
print(x)
print()
y = np.insert(x,2,3) # (variable of array, index value where you want to insert data, insert data which you want to add)
print(y)

[1 2 5 7]

[1 2 3 5 7]


In [117]:
# We can insert data at multiple indexes in an array.
x = np.array([1,2,5,7])
print(x)
print()
y = np.insert(x,(2,4),40) # (variable of array, index value where you want to insert data, insert data which you want to add)
print(y)

[1 2 5 7]

[ 1  2 40  5  7 40]


In [118]:
# We can insert data at multiple indexes in an array.
x = np.array([1,2,5,7])
print(x)
print()
y = np.insert(x,(2,4),(40,10)) # (variable of array, index value where you want to insert data, insert data which you want to add)
print(y)

[1 2 5 7]

[ 1  2 40  5  7 10]


In [120]:
# Note:- always insert a same data type as array because it doesn't accept changed data type like float, string etc.
x = np.array([1,2,5,7])
print(x)
print()
y = np.insert(x,2,"k") # (variable of array, index value where you want to insert data, insert data which you want to add)
print(y)

[1 2 5 7]



ValueError: invalid literal for int() with base 10: 'k'

In [121]:
# Example of 2D Array
x = np.array([[1,2],[5,5]])
y = np.insert(x,1,5)
print(y)

[1 5 2 5 5]


In [124]:
# Example of 2D Array with axis
# We can insert multiple data at multiple indexes.
x = np.array([[1,2],[5,5]])
y = np.insert(x,[1,0],5,axis=1)
print(y)

[[5 1 5 2]
 [5 5 5 5]]


# np.append()

In [127]:
# It add the data in the last of an array.
# We can add any data type in the array.
# In Insert function we can add only the same data type in the array but in append function we can add any data type.
# Example of 1D array.
x = np.array([1,5,5,2])
y = np.append(x,[5.54,"g"])
print(y)

['1' '5' '5' '2' '5.54' 'g']


In [141]:
# Example of 2D array.
x = np.array([[1,2],[2,5],[8,4]])
y = np.append(x,[[7,4]],axis=0)
print(y)

[[1 2]
 [2 5]
 [8 4]
 [7 4]]


# np.delete() 

In [142]:
x = np.array([1,5,5,65,2])
y = np.delete(x,2) # (variable of array, index value of item which you want to delete)
print(y)

[ 1  5 65  2]


# np.matrix()

In [143]:
# How to create matrix
x = np.matrix([[1,2,3],[5,9,7]])
print(x)
print(type(x))

[[1 2 3]
 [5 9 7]]
<class 'numpy.matrix'>


In [144]:
x = np.array([[1,2,3],[5,9,7]])
print(x)
print(type(x))

[[1 2 3]
 [5 9 7]]
<class 'numpy.ndarray'>


In [146]:
# Addition of 2 matrix
x = np.matrix([[1,2,3],[5,9,7]])
y = np.matrix([[4,5,6],[5,7,1]])
print(x+y)

[[ 5  7  9]
 [10 16  8]]


In [147]:
# subtraction of 2 matrix
x = np.matrix([[1,2,3],[5,9,7]])
y = np.matrix([[4,5,6],[5,7,1]])
print(x-y)

[[-3 -3 -3]
 [ 0  2  6]]


In [151]:
# Multiplication between 2 matrix
x = np.matrix([[1,2],[5,9]])
y = np.matrix([[4,5],[5,7]])
print(x*y)

[[14 19]
 [65 88]]


In [152]:
# We use .dot() for multiply in matrix
x = np.matrix([[1,2],[5,9]])
y = np.matrix([[4,5],[5,7]])
print(x.dot(y))

[[14 19]
 [65 88]]


# Matrix Functions In Numpy :-
# Transpose / np.transpose() :- it will change the axis of matrix
# Swapaxes / np.swapaxes() :- it will also change the axis of matrix but axis value should be enter.
# Inverse / np.linalg.inv() :- it will inverse the matrix
# Power / np.linalg.matrix_power() 
# Determinate / np.linalg.det() :- it will give determinator of given matrix 

In [168]:
# Example of np.transpose()
x = np.matrix([[1,2],[1,5]])
print(x)
print()
print(np.transpose(x))
print()
print(x.T) # Shortcut of np.transpose(). (variable of matrix,T)

[[1 2]
 [1 5]]

[[1 1]
 [2 5]]

[[1 1]
 [2 5]]


In [161]:
#Example of np.swapaxes()
x = np.matrix([[1,5,25],[52,5,2]])
print(x)
print()
print(np.swapaxes(x,1,0)) # (variable of matrix, axis which you to swap, axis with)

[[ 1  5 25]
 [52  5  2]]

[[ 1 52]
 [ 5  5]
 [25  2]]


In [165]:
# Example of np.linalg.inv()
x = np.matrix([[1,5],[4,5]])
print(np.linalg.inv(x))

[[-0.33333333  0.33333333]
 [ 0.26666667 -0.06666667]]


In [6]:
# Example of np.linalg.matrix_power()
x = np.matrix([[1,2],[2,8]])
print(x)
print()

print(np.linalg.matrix_power(x,2)) # n>0, it gives power of given 
print()
print(np.linalg.matrix_power(x,0)) # n=0, show 1 diagonally
print()
print(np.linalg.matrix_power(x,-1)) # n<0, it gives power to inverse matrix

[[1 2]
 [2 8]]

[[ 5 18]
 [18 68]]

[[1 0]
 [0 1]]

[[ 2.   -0.5 ]
 [-0.5   0.25]]


In [11]:
# Example of np.linalg.det()
x = np.matrix([[1,2,9,4],[2,8,4,1],[2,5,5,6],[9,1,5,2]])
print(x)
print()
print(np.linalg.det(x))

[[1 2 9 4]
 [2 8 4 1]
 [2 5 5 6]
 [9 1 5 2]]

2287.000000000001
