# Dropout Regularization in Deep Neural Network

In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [59]:
df = pd.read_csv(r'Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [60]:
df.shape

(150, 6)

In [61]:
df.Species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [62]:
df['Species'] = df['Species'].replace(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], [0,1,2])

In [63]:
X = df.drop(['Id','Species'],axis=1)
y = df['Species']

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [66]:
X_train.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
96             5.7           2.9            4.2           1.3
105            7.6           3.0            6.6           2.1
66             5.6           3.0            4.5           1.5
0              5.1           3.5            1.4           0.2
122            7.7           2.8            6.7           2.0

In [67]:
X_test.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4

In [68]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# Using Deep Learning Model

### Model without using Dropout

In [69]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [70]:
model = Sequential([
    Dense(68, input_dim=4, activation='relu'),
    Dense(1, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 6ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 5/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accura

In [71]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 0.3000


[0.0, 0.30000001192092896]

**Training Accuracy >>> Test Accuracy**

In [72]:
y_pred = model.predict(X_test).reshape(-1)
print("Predicted Probabilities:")
print(y_pred[:10])

y_pred_rounded = np.round(y_pred)
print("Rounded Predictions (0 or 1):")
print(y_pred_rounded[:10])

2/2 [==============================] - 0s 8ms/step
Predicted Probabilities:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Rounded Predictions (0 or 1):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [73]:
y_test[:10]

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: Species, dtype: int64

In [74]:
from sklearn.metrics import confusion_matrix, classification_report

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.30      1.00      0.46        15
           2       0.00      0.00      0.00        16

    accuracy                           0.30        50
   macro avg       0.10      0.33      0.15        50
weighted avg       0.09      0.30      0.14        50

Confusion Matrix:
[[ 0 19  0]
 [ 0 15  0]
 [ 0 16  0]]


# Model with using Dropout

In [75]:
model = Sequential([
    Dense(60, input_dim=4, activation='relu'),
    Dropout(0.3),
    Dense(30, activation='relu'),
    Dropout(0.3),
    Dense(15, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 2s 6ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 7/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 0.3500
Epoch 10/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accura

In [76]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 0.3000


[0.0, 0.30000001192092896]

In [77]:
y_pred = model.predict(X_test).reshape(-1)
print("Predicted Probabilities:")
print(y_pred[:10])

y_pred_rounded = np.round(y_pred)
print("Rounded Predictions (0 or 1):")
print(y_pred_rounded[:10])

2/2 [==============================] - 0s 7ms/step
Predicted Probabilities:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Rounded Predictions (0 or 1):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [78]:
y_test[:10]

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: Species, dtype: int64

In [79]:
# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.30      1.00      0.46        15
           2       0.00      0.00      0.00        16

    accuracy                           0.30        50
   macro avg       0.10      0.33      0.15        50
weighted avg       0.09      0.30      0.14        50

Confusion Matrix:
[[ 0 19  0]
 [ 0 15  0]
 [ 0 16  0]]
