In [1]:
import statistics as sts

In [2]:
# mean, median, mode

In [20]:
val = [4,8,6,5,5]

In [21]:
# means
sts.mean(val)

5.6

In [22]:
# median
sts.median(val)

5

In [23]:
#mode
sts.mode(val)

5

In [24]:
import numpy as np

In [25]:
# mean
np.average(val)

5.6

In [26]:
#range
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
# range
w = np.arange(5,10)
w

array([5, 6, 7, 8, 9])

In [28]:
# weighted average
np.average(val,weights=w)

5.571428571428571

In [29]:
# Spread: min, max, range, variance, std dev

In [32]:
# min value
min = np.min(val)
min

4

In [33]:
# max value
max = np.max(val)
max

8

In [35]:
# range
range = max-min
range

4

In [38]:
from statistics import variance
from statistics import stdev

In [39]:
#variance
sts.variance(val)

2.3

In [40]:
#Standard Deviation
sts.stdev(val)

1.51657508881031

In [47]:
x= np.arange(10,20)
y = np.array([20,59,78,62,23,1,89,92,5,5])

# covariance matrix
np.cov(x,y)

array([[   9.16666667,  -21.33333333],
       [ -21.33333333, 1326.48888889]])

In [48]:
#pearson's correlation
np.corrcoef(x,y)

array([[ 1.        , -0.19346446],
       [-0.19346446,  1.        ]])

In [49]:
import scipy.stats

#pearson's correlation
scipy.stats.pearsonr(x,y)

PearsonRResult(statistic=-0.19346445819711314, pvalue=0.5922838209972693)

In [50]:
#spearman's rank correlation
scipy.stats.spearmanr(x,y)

SpearmanrResult(correlation=-0.1580554413568168, pvalue=0.6627622972444478)

In [51]:
#percentile
np.percentile(y,25)

8.75

In [52]:
np.percentile(y,50)

41.0

In [53]:
np.percentile(y,75)

74.0